# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build-base:
    desc: Build the base image
    cmd: docker build
          -t base:local
          -f base.Dockerfile
          --build-arg USERNAME=vscode
          --build-arg NODE_VERSION=24
          .
    silent: true

  build-node:
    desc: Build the Node.js image
    cmd: docker build -t node:local -f node.Dockerfile .
    silent: true

  build-universal:
    desc: Build the universal image
    cmd: docker build -t universal:local -f universal.Dockerfile .
    silent: true

  start-base:
    desc: Start a container from the base image
    cmd: docker run --rm -it base:local bash
    silent: true

  start-node:
    desc: Start a container from the Node.js image
    cmd: docker run --rm -it node:local bash
    silent: true

  start-universal:
    desc: Start a container from the universal image
    cmd: docker run --rm -it universal:local bash
    silent: true

  test-base:
    desc: Build and test the base image (includes Trivy)
    cmd: ./tests/run.sh base
    silent: true

  test-node:
    desc: Build and test the node image (includes Trivy)
    cmd: ./tests/run.sh node
    silent: true

  test-universal:
    desc: Build and test the universal image (includes Trivy)
    cmd: ./tests/run.sh universal
    silent: true

  test-all:
    desc: Build and test all images (includes Trivy)
    cmd: ./tests/run.sh all
    silent: true
