# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  build-base:
    desc: Build the base image
    cmd: docker build
          -t base:local
          -f base.Dockerfile
          --build-arg USERNAME=vscode
          --build-arg NODE_VERSION=24
          .
    silent: true

  build-node:
    desc: Build the Node.js image
    cmd: docker build -t typescript-node:local -f typescript-node.Dockerfile .
    silent: true

  build-universal:
    desc: Build the universal image
    cmd: docker build -t universal:local -f universal.Dockerfile .
    silent: true

  start-base:
    desc: Start a container from the base image
    cmd: docker run --rm -it base:local bash
    silent: true

  start-node:
    desc: Start a container from the Node.js image
    cmd: docker run --rm -it typescript-node:local bash
    silent: true

  start-universal:
    desc: Start a container from the universal image
    cmd: docker run --rm -it universal:local bash
    silent: true
