name: images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '*.Dockerfile'
      - 'tests/**'
      - 'test.sh'
      - '.github/workflows/**'
  schedule:
    - cron: '0 0 * * 2'

jobs:
  build-base:
    uses: oxybot/dev-containers/.github/workflows/_build-test-push.yaml@main
    with:
      image: base
      dockerfile: base.Dockerfile
      cache_scope: base

  build-node:
    uses: oxybot/dev-containers/.github/workflows/_build-test-push.yaml@main
    needs: build-base
    with:
      image: node
      dockerfile: node.Dockerfile
      cache_scope: node
      extra_tags: |
        type=raw,value=24,enable={{is_default_branch}}

  build-universal:
    uses: oxybot/dev-containers/.github/workflows/_build-test-push.yaml@main
    needs: build-node
    with:
      image: universal
      dockerfile: universal.Dockerfile
      cache_scope: universal
